name: Slack Notification
on:
  push:
  pull_request:
  issue_comment:
  issues:
  pull_request_review:
  pull_request_review_comment:
  pull_request_target:
  discussion:
  discussion_comment:
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Slack
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"${{ github.event.head_commit.message }}"}' $SLACK_WEBHOOK_URL
